version: "3.9"

services:
  web:
    build: .
    command: gunicorn djangoapp.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
