version: "3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py loaddata twitter_users.json && python manage.py scrape_profile_pics && python manage.py collectstatic --noinput && gunicorn pridebot.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
