# syntax=docker/dockerfile:1
FROM python:3.10.5-slim-buster
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN \
#apt-get install postgresql-libs && \
	apt-get update && \
	apt-get install -y gcc musl-dev postgresql-server-dev-all && \
	python3 -m pip install -r requirements.txt
COPY . /code/
