version: "3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py scrape_profile_pics && gunicorn pridebot.wsgi:application --bind 0.0.0.0:80 --workers 3"
    volumes:
      - .:/code
    ports:
      - "80:80"
    env_file:
      - .env
