# Generated by Django 4.0.5 on 2022-06-06 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0002_twitterprofilepic_delete_twitterprofilepics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUserCurrentProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_profile_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterbot.twitterprofilepic')),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterbot.twitteruser')),
            ],
        ),
    ]
