# Generated by Django 4.0.5 on 2022-06-07 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0003_twitterusercurrentprofilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterusercurrentprofilepic',
            name='current_profile_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitterbot.twitterprofilepic'),
        ),
    ]
