# Generated by Django 4.0.5 on 2022-06-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0004_alter_twitterusercurrentprofilepic_current_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterprofilepic',
            name='local_path',
        ),
        migrations.AddField(
            model_name='twitterprofilepic',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='profile_pictures'),
        ),
    ]
